### PR TITLE
 Provide alternative JEP installation instructions

### PR DESCRIPTION
**Pull request by pedrorijo91**
Don't merge. Ongoing work

**EDIT:** mergeable

### CODE REVIEW

**Comment by nmldiegues** [comment]
@pedrorijo91  that alternative link does not solve the full thing since it compiles the library but does not explain the necessary environment variables that need to be set (as we indicate in our more explicit configuration guide)

What's the end goal here?

**Comment by pedrorijo91** [comment]
@nmldiegues, during the installation of the scikit provider we faced problems while installing jep through `pip`. As recommended by @henriquevcosta, we followed the instructions on the link, by cloning the JEP repo, and executing the recommended `python setup.py build install`, we could solve the problem, and proceed to step 6

**Comment by nmldiegues** [comment]
@pedrorijo91  what's the idea here? Is this still WIP ?

**Comment by pedrorijo91** [comment]
@nmldiegues  yes, will have a second look at this soon, and add a bit more information eventually. Will ping you as soon as it's ready for a review

**Comment by pedrorijo91** [comment]
@nmldiegues I think this can be useful as it is, even if in the future gets improved

**Comment by nmldiegues** [comment]
@pedrorijo91  can we also add a link to the following? https://github.com/feedzai/oracle-jep-miniconda  I think it is useful

**Comment by pedrorijo91** [comment]
@nmldiegues agree. Just added a small sentence on that

**Comment by nmldiegues** [comment]
Merged!

**Pull request merged**
